# Generated by Django 2.1 on 2020-06-10 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0005_auto_20200609_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_connected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbapp.PhotoPost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
